import { Team } from '@/types/sports.types';

export const dummyTeamData: Team[] = [
    {
        id: `PremierLeague-home_team`,
        name: 'Home Team',
        wins: 0,
        losses: 0,
        points: 0,
        draws: 0,
        gamesPlayed: 0,
        selectable: true,
        playedAgainst: [],
    },
    {
        id: `PremierLeague-away_team`,
        name: 'Away Team',
        wins: 0,
        losses: 0,
        points: 0,
        draws: 0,
        gamesPlayed: 0,
        selectable: true,
        playedAgainst: [],
    },
    {
        id: `PremierLeague-manchester_united`,
        name: 'Manchester United',
        wins: 2,
        losses: 0,
        points: 7,
        draws: 1,
        gamesPlayed: 3,
        selectable: false,
        playedAgainst: ['PremierLeague-liverpool', 'PremierLeague-arsenal', 'PremierLeague-chelsea'],
    },
    {
        id: `PremierLeague-liverpool`,
        name: 'Liverpool',
        wins: 2,
        losses: 1,
        points: 6,
        draws: 0,
        gamesPlayed: 3,
        selectable: false,
        playedAgainst: ['PremierLeague-manchester_united', 'PremierLeague-arsenal', 'PremierLeague-chelsea'],
    },
    {
        id: `PremierLeague-arsenal`,
        name: 'Arsenal',
        wins: 1,
        losses: 1,
        points: 5,
        draws: 2,
        gamesPlayed: 3,
        selectable: false,
        playedAgainst: ['PremierLeague-manchester_united', 'PremierLeague-liverpool', 'PremierLeague-chelsea'],
    },
    {
        id: `PremierLeague-chelsea`,
        name: 'Chelsea',
        wins: 1,
        losses: 1,
        points: 4,
        draws: 1,
        gamesPlayed: 3,
        selectable: false,
        playedAgainst: ['PremierLeague-manchester_united', 'PremierLeague-liverpool', 'PremierLeague-arsenal'],
    },
];
