import { Team } from '@/types/sports.types';

export const wimbledonData: Team[] = [
    {
        id: `Wimbledon-Djokovic`,
        name: 'Djokovic',
        wins: 5,
        losses: 4,
        points: 15,
        draws: 0,
        gamesPlayed: 9,
        playedAgainst: [],
        scoreHistory: [],
    },
    {
        id: `Wimbledon-Alcaraz`,
        name: 'Alcaraz',
        wins: 4,
        losses: 3,
        points: 12,
        draws: 0,
        gamesPlayed: 7,
        playedAgainst: [],
        scoreHistory: [],
    },
    {
        id: `Wimbledon-Nadal`,
        name: 'Nadal',
        wins: 3,
        losses: 3,
        points: 9,
        draws: 0,
        gamesPlayed: 6,
        playedAgainst: [],
        scoreHistory: [],
    },
    {
        id: `Wimbledon-Murray`,
        name: 'Murray',
        wins: 2,
        losses: 3,
        points: 6,
        draws: 0,
        gamesPlayed: 5,
        playedAgainst: [],
        scoreHistory: [],
    },
    {
        id: `Wimbledon-Zverev`,
        name: 'Zverev',
        wins: 1,
        losses: 3,
        points: 3,
        draws: 0,
        gamesPlayed: 4,
        playedAgainst: [],
        scoreHistory: [],
    },
];
