import type { Metadata } from 'next';
import { Inter, Roboto, Montserrat, Bebas_Neue } from 'next/font/google';
import StoreProvider from '@/providers/StoreProvider';
import './globals.css';

const inter = Inter({
    variable: '--font-inter',
    subsets: ['latin'],
});

const roboto = Roboto({
    variable: '--font-roboto',
    subsets: ['latin'],
});

const montserrat = Montserrat({
    variable: '--font-montserrat',
    subsets: ['latin'],
});

const bebasNeue = Bebas_Neue({
    variable: '--font-bebas-neue',
    subsets: ['latin'],
    weight: ['400'],
});

export const metadata: Metadata = {
    title: 'Sports SPA',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.variable} ${roboto.variable} ${montserrat.variable} ${bebasNeue.variable} antialiased`}
            >
                <StoreProvider>{children}</StoreProvider>
            </body>
        </html>
    );
}
